### ISSUE TITLE
[QUESTION] Why don't you just update Node.js?

### ISSUE THREAD

**Issue by zardoy** [Stremio/ytdl-core-blob#4]
Hey, why do you call engine requirement of Node.js >=10 **irrational**? Why don't you just update the version of Node.js? I'm just curious. newer version of Node.js has a lot of great features and as a bonus it enables you to use new ES features such as optional chaining which is obviously makes your bundle a little smaller. I can see that a lot of great libraries dropping support for old Node.js versions and I like it (you don't need to care about old Node.js bugs)

**Comment by jaruba** [comment]
This project is actually not used anymore, we already updated Node and use the official `ytdl-core` module now. The blob was just used as a temporary workaround in our app as updating node can (in general) bring many tasks of compatibility with it, especially on very large projects like our's.

**Comment by jaruba** [comment]
As for the question of why I called it "irrational", it's because `ytdl-core` did not need to set that minimum node version limit, it worked perfectly fine with (much) older node versions as well, which is why setting that version requirement was, in all actuality, irrational.

**Comment by zardoy** [comment]
Okay, I got you. Thank you for the quick response!
